version: '3.3'

services:
  app:
    image: golang:1.11-alpine
    volumes:
      - .:/go/src/banwire/services/gs_ivr_tokenization
    working_dir: /go/src/banwire/services/gs_ivr_tokenization
    command: go build -o bin_ivrmsi/gs_ivr-${ENV:-prod} 
