version: '3.3'

services:
  app:
    image: golang:1.11-alpine
    volumes:
      - .:/go/src/banwire/services/banwire_cotiza
    working_dir: /go/src/banwire/services/banwire_cotiza
    command: go build -o bin_banwire_cotiza/cotizador-${ENV:-prod} 
